# Generated by Django 4.0.5 on 2022-11-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_advocate_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
